defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: rordev
  password: roruser

development:
  <<: *defaults
  database: oauth_provider_api_dev

test:
  <<: *defaults
  database: oauth_provider_api_test

production:
  <<: *defaults
  database: oauth_provider_api_prod